### ISSUE TITLE
Изменить структуру документации, добавив methodmap

### ISSUE THREAD

**Issue by TiBarification** [FD-Forks/Shop-Core#10]
Конвертирование native в methodmap. Внедрить работу с кастомными типами.
Для `CategoryId`,`ItemId`,`ItemType` и т.д. создать **methodmap**.

**Comment by CrazyHackGUT** [comment]
Ещё нужно комментарии ко всему, где это возможно, добавить, чтобы можно было веб доку по апи нормально построить.
