### ISSUE TITLE
Поддержка других валют

### ISSUE THREAD

**Issue by Truyn** [FD-Forks/Shop-Core#104]
Почему бы не добавить поддержку личных кабинетов как дополнительной валюты?.

Я вкурсе по shop gold но почему бы это не сделать в основной версии.

**Comment by IL0co** [comment]
Можно коственно это сделать, через модуль (у меня есть такой :D), так же модно сделать и в коре, напомните мне вечером в телегу или дискорд, я добавляю эту идею в свой список TODO для улучшения ядра шопа.

**Comment by TiBarification** [comment]
Поддержка дополнительных валют не планируется в данной версии магазина. Расширение до второй валюты имеет только Shop Gold. В активном тестировании бесконечная вложенность категорий, так же на Shop Gold версии.

Наиболее удобным решением по моему мнению является [хук покупки предмета](https://github.com/FD-Forks/Shop-Core/blob/master/addons/sourcemod/scripting/include/shop/items.inc#L61) и наложение на него дополнительных условий приобретения. Таким образом вы можете поставить цену покупки бесплатно, в описании написать зависимости для приобретения и влиять на покупку.
