### ISSUE TITLE
Items not being removed from database. 

### ISSUE THREAD

**Issue by pedrotski** [FD-Forks/Shop-Core#105]
**Describe the bug**
Removing items from the shop config does not delete them from the database. This is the error that happens when someone who owns that item joins the server again. 

It's like its still trying to apply that item on the player.

`EXCEPTION_ACCESS_VIOLATION_READ accessing 0x16c

Thread 0 (crashed):
   0: dbi.mysql.ext.dll!my_real_read [ net_serv.cc:839 + 0x2 ]
      eip: 0x258709a8  esp: 0x00f8cedc  ebp: 0xffffffff  ebx: 0x25059d20
      esi: 0x25059950  edi: 0x00000004  eax: 0x00000000  ecx: 0x37372f9b
      edx: 0x00000000  efl: 0x00010286  

      2587099d  8b e8              mov ebp, eax
      2587099f  83 c4 0c           add esp, 0xc
      258709a2  85 ed              test ebp, ebp
      258709a4  7f 60              jg 0x25870a06
      258709a6  8b 06              mov eax, [esi]
  >   258709a8  8b 90 6c 01 00 00  mov edx, [eax+0x16c]
      258709ae  50                 push eax
      258709af  ff d2              call edx
      258709b1  83 c4 04           add esp, 0x4
      258709b4  85 ed              test ebp, ebp
      258709b6  7d 15              jge 0x258709cd

      00f8cedc  90 bc e6 24 68 cf f8 00  b0 73 f5 23 ff ff ff ff  ...$h....s.#....
      00f8ceec  00 00 00 00 da 0a 87 25                           .......%        

      Found via instruction pointer in context
`

**To Reproduce**
1. Remove item from store
2. See its not removed from database

**Expected behavior**
The item to be removed from the database.

**Server (please complete the following information):**
Windows Server 2019
Mysql db 5.4 running on linux

**Comment by TiBarification** [comment]
Removing item as plugin does not guarantee that it might be removed from database.

You need to do these steps to remove it properly.
- Disable module with expected item
- Go to database, find in `shop_items` table item you want to remove, remember it's `id`
- Go to `shop_boughts` table remove rows related to that item
- Remove rows with item in `shop_items` and `shop_toggle`

Hope it is answering your question.

**Comment by pedrotski** [comment]
> Removing item as plugin does not guarantee that it might be removed from database.
> 
> You need to do these steps to remove it properly.
> 
> * Disable module with expected item
> * Go to database, find in `shop_items` table item you want to remove, remember it's `id`
> * Go to `shop_boughts` table remove rows related to that item
> * Remove rows with item in `shop_items` and `shop_toggle`
> 
> Hope it is answering your question.

Perfect! I wasn't sure if there was something wrong. Thanks a lot.
