### ISSUE TITLE
Add portuguese translation

### ISSUE THREAD

**Issue by ZeSpama** [FD-Forks/Shop-Core#109]
I've translated you'r shop core plugin and i wanted to share with you the translation.

Here is the portuguese translation.
[shop.phrases.txt](https://github.com/FD-Forks/Shop-Core/files/7456814/shop.phrases.txt)

**Comment by TiBarification** [comment]
> I've translated you'r shop core plugin and i wanted to share with you the translation.
> 
> Here is the portuguese translation.
> [shop.phrases.txt](https://github.com/FD-Forks/Shop-Core/files/7456814/shop.phrases.txt)

Thank you for your contribution. Can you create pull request for it?

**Comment by TiBarification** [comment]
Added via #111
