### ISSUE TITLE
I can't complie this plugin

### ISSUE THREAD

**Issue by hanicsgo** [FD-Forks/Shop-Core#113]
//// shop.sp
//
// F:\file Alast\steamcmd\steamcmd\csgoserver5\csgo\addons\sourcemod\scripting\include\regex.inc(175) : error 147: new-style declarations are required
// shop/admin.sp(7) : error 001: expected token: "{", but found "struct"
// shop/admin.sp(9) : error 001: expected token: "public", but found "int"
// shop/admin.sp(10) : error 001: expected token: "}", but found "int"
// shop/admin.sp(12) : error 054: unmatched closing brace ("}")
// shop/admin.sp(21) : error 139: could not find type "DataPackPos"
// shop/admin.sp(22) : error 139: could not find type "DataPackPos"
// shop/admin.sp(22) : error 139: could not find type "DataPackPos"
// shop/admin.sp(23) : error 139: could not find type "DataPackPos"
// shop/admin.sp(23) : error 139: could not find type "DataPackPos"
// shop/admin.sp(140) : error 017: undefined symbol "g_iOpt"
// shop/admin.sp(140) : warning 215: expression has no effect
// shop/admin.sp(140) : error 001: expected token: ";", but found "]"
// shop/admin.sp(140) : error 029: invalid expression, assumed zero
// shop/admin.sp(140) : fatal error 189: too many error messages on one line
//
// Compilation aborted.
// 14 Errors.
//
// Compilation Time: 0.58 sec

How can i fix this, thanks u guys

**Comment by R1KO** [comment]
@hanicsgo which sourcemod compiler version?

**Comment by hanicsgo** [comment]
@R1KO i used SM 1.10.0.6549
