### ISSUE TITLE
проблема с кодировкой

### ISSUE THREAD

**Issue by Truyn** [FD-Forks/Shop-Core#133]
![image](https://user-images.githubusercontent.com/53527324/166108714-83d0f3d2-0d30-4971-85c3-d656fbabffba.png)

Беда с некоторыми никами и товарами что имеют имя в кириллице

**Comment by Truyn** [comment]
![image](https://user-images.githubusercontent.com/53527324/166108742-7bb04421-9bbd-4b56-a7e5-0d1f417cbad0.png)

**Comment by Truyn** [comment]
Сопоставления не менял, это после обнов

**Comment by Truyn** [comment]
Предметы что были нормальные, заново продублировались уже со сбитой кодировкой

![image](https://user-images.githubusercontent.com/53527324/166108892-bfee5368-9e15-4476-8e5b-925a6fb86c60.png)

**Comment by Truyn** [comment]
Вероятно баг происходит при загрузке/выгрузке плагина

**Comment by TiBarification** [comment]
English only.
