### ISSUE TITLE
error Blaming: shop.smx

### ISSUE THREAD

**Issue by Truyn** [FD-Forks/Shop-Core#134]
L 05/05/2022 - 20:14:25: [SM] Exception reported: Invalid Handle a8d07eb (error: 1)
L 05/05/2022 - 20:14:25: [SM] Blaming: shop.smx
L 05/05/2022 - 20:14:25: [SM] Call stack trace:
L 05/05/2022 - 20:14:25: [SM]   [0] ArrayList.FindValue
L 05/05/2022 - 20:14:25: [SM]   [1] Line 717, addons/sourcemod/scripting/shop/item_manager.sp::ItemManager_OnItemRegistered
L 05/05/2022 - 20:14:25: [SM] Exception reported: Invalid Handle a8d07eb (error: 1)
L 05/05/2022 - 20:14:25: [SM] Blaming: shop.smx
L 05/05/2022 - 20:14:25: [SM] Call stack trace:
L 05/05/2022 - 20:14:25: [SM]   [0] ArrayList.FindValue
L 05/05/2022 - 20:14:25: [SM]   [1] Line 717, addons/sourcemod/scripting/shop/item_manager.sp::ItemManager_OnItemRegistered
L 05/05/2022 - 20:14:25: [SM] Exception reported: Invalid Handle a8d07eb (error: 1)
L 05/05/2022 - 20:14:25: [SM] Blaming: shop.smx
L 05/05/2022 - 20:14:25: [SM] Call stack trace:
L 05/05/2022 - 20:14:25: [SM]   [0] ArrayList.FindValue
L 05/05/2022 - 20:14:25: [SM]   [1] Line 717, addons/sourcemod/scripting/shop/item_manager.sp::ItemManager_OnItemRegistered
L 05/05/2022 - 20:14:25: [SM] Exception reported: Invalid Handle a8d07eb (error: 1)
L 05/05/2022 - 20:14:25: [SM] Blaming: shop.smx
L 05/05/2022 - 20:14:25: [SM] Call stack trace:
L 05/05/2022 - 20:14:25: [SM]   [0] ArrayList.FindValue
L 05/05/2022 - 20:14:25: [SM]   [1] Line 717, addons/sourcemod/scripting/shop/item_manager.sp::ItemManager_OnItemRegistered
L 05/05/2022 - 20:14:25: [SM] Exception reported: Invalid Handle a8d07eb (error: 1)
L 05/05/2022 - 20:14:25: [SM] Blaming: shop.smx
L 05/05/2022 - 20:14:25: [SM] Call stack trace:
L 05/05/2022 - 20:14:25: [SM]   [0] ArrayList.FindValue
L 05/05/2022 - 20:14:25: [SM]   [1] Line 717, addons/sourcemod/scripting/shop/item_manager.sp::ItemManager_OnItemRegistered
L 05/05/2022 - 20:14:25: [SM] Exception reported: Invalid Handle a8d07eb (error: 1)
L 05/05/2022 - 20:14:25: [SM] Blaming: shop.smx
L 05/05/2022 - 20:14:25: [SM] Call stack trace:
L 05/05/2022 - 20:14:25: [SM]   [0] ArrayList.FindValue
L 05/05/2022 - 20:14:25: [SM]   [1] Line 717, addons/sourcemod/scripting/shop/item_manager.sp::ItemManager_OnItemRegistered
L 05/05/2022 - 20:14:26: [SM] Exception reported: Invalid Handle a8d07eb (error: 1)
L 05/05/2022 - 20:14:26: [SM] Blaming: shop.smx
L 05/05/2022 - 20:14:26: [SM] Call stack trace:
L 05/05/2022 - 20:14:26: [SM]   [0] ArrayList.FindValue
L 05/05/2022 - 20:14:26: [SM]   [1] Line 717, addons/sourcemod/scripting/shop/item_manager.sp::ItemManager_OnItemRegistered
L 05/05/2022 - 20:14:26: [SM] Exception reported: Invalid Handle a8d07eb (error: 1)
L 05/05/2022 - 20:14:26: [SM] Blaming: shop.smx
L 05/05/2022 - 20:14:26: [SM] Call stack trace:
L 05/05/2022 - 20:14:26: [SM]   [0] ArrayList.FindValue
L 05/05/2022 - 20:14:26: [SM]   [1] Line 717, addons/sourcemod/scripting/shop/item_manager.sp::ItemManager_OnItemRegistered
L 05/05/2022 - 20:50:52: Error log file session closed.

**Comment by TiBarification** [comment]
Please, use template to submit an issue.
https://github.com/FD-Forks/Shop-Core/issues/new?assignees=&labels=&template=Bug_report.md
