### ISSUE TITLE
Просьба выдать мне бан в этом репозитории так как я вижу

### ISSUE THREAD

**Issue by Truyn** [FD-Forks/Shop-Core#135]
1

**Comment by Truyn** [comment]
Бля еще и русофобы на форуме модераторы, clown edition

**Comment by Truyn** [comment]
![LbrmnmeU93hcL9M78c7lgYI9nY24ZD9AuWYmi0EEfcOMojTwjxDTNkGgG3HJkMY1v81YXo0qqPuO8SHBq_nVbrcZ](https://user-images.githubusercontent.com/53527324/167265194-854d2867-ab09-4b24-82ff-202ca4d5c9d3.jpg)

Когда на форуме пишешь на русском)
Когда отвечали до этих событий на русском).

Да уж 
![image](https://user-images.githubusercontent.com/53527324/167265208-8f5c9358-01b6-4ee8-a78a-dfbf995c00d5.png)
![image](https://user-images.githubusercontent.com/53527324/167265226-7718e126-f818-41f5-818e-a049654e1ff2.png)

**Comment by Truyn** [comment]
Никогда не был украинофобом но это пиздец, как можно быть настолько субьективным?

**Comment by IL0co** [comment]
> Бля еще и русофобы на форуме модераторы, clown edition

На гитхабе заведено всё обсуждать на английском, потому что большая часть пользователей - не русскоговорящие, и что бы они не пользовались переводчиком, было принято писать на английском.

**Comment by R1KO** [comment]
Просьба удовлетворена, закрываем
