### ISSUE TITLE
При передаче предмета со сроком "Навсегда", он сразу истекает

### ISSUE THREAD

**Issue by CrazyHackGUT** [FD-Forks/Shop-Core#24]
Перенесено [отсюда](http://hlmod.ru/posts/260236/).
> Такой баг, что когда предмет "Навсегда", после того как его передали кому-либо из игроков, пишет что "Срок действия предмета истек"
В итоге не у того кому передавал, и не у того кто передал вещи(ей) просто нет..
Серьезная проблема :c

**Comment by Exle13** [comment]
Такого бага не было замечено даже на **2.2.0**

**Comment by TiBarification** [comment]
Единичный случай получается.
