### ISSUE TITLE
Показ страниц в шопе.

### ISSUE THREAD

**Issue by samoletik1337** [FD-Forks/Shop-Core#25]
Думаю было бы неплохо добавить показ страниц, то есть при просмотре вещей в определенной категории писалось бы сверху номер страницы , например 2/10 , то есть 2 страница из 10. Нужна такая фича, чтобы при покупке определенной вещи , в следующий раз не искать на какой он странице. Это было бы полезно тем , у кого много вещей в одной категории.

**Comment by CrazyHackGUT** [comment]
Меню итемов в категории реализовано, вроде, посредством стандартных SM менюшек. Сомневаюсь, что такое возможно. Именно при каждом нажатии на "Далее"/"Назад".

**Comment by R1KO** [comment]
Могу в заглавие меню добавить

**Comment by TiBarification** [comment]
Не востребовано.
