### ISSUE TITLE
Single use item

### ISSUE THREAD

**Issue by TiBarification** [FD-Forks/Shop-Core#30]
Add ItemType_SingleUse, it is like `Item_BuyOnly`, but it can be used only once.

**Comment by IL0co** [comment]
> Add ItemType_SingleUse, it is like `Item_BuyOnly`, but it can be used only once.

I would implement `ItemType_SingleUse` inside the plugin, which is required or by the module, by checking the amount that is in the` Shop_OnItemBuy` forward and limit if it is exceeded, the Type of the item will be `Item_Finite`

**Comment by TiBarification** [comment]
I know it could be a module, but it is better to have a solution of this scope from our side, instead of copying that logic in each module and simulating through ItemType_Finite

**Comment by R1KO** [comment]
@TiBarification вопрос в том насколько она нужна чтобы добавлять её в кор

**Comment by TiBarification** [comment]
maybe it is really bad idea
