### ISSUE TITLE
Item Registration may fail

### ISSUE THREAD

**Issue by CrazyHackGUT** [FD-Forks/Shop-Core#53]
**Describe the bug**
Item can't be registered, if him name contains any quote symbol.

**To Reproduce**
1. Change in any module itemname to `I broke' everything'`
2. Compile.
3. Run.
4. Check error logs.

Item don't be registered because Shop Core can't check item existing in DB.

**Expected behavior**
Shop Core should escape all quote characters and create item, if not exists.

https://github.com/FD-Forks/Shop-Core/blob/4ff634c38d00878f6651cac4770ed59e849e8728/addons/sourcemod/scripting/shop/item_manager.sp#L626-L629
Item name should be escaped.

**Comment by CrazyHackGUT** [comment]
_Moved from [HLmod](https://hlmod.ru/posts/381976)_

**Comment by TiBarification** [comment]
Do we need to replace those formats to [SQL_FormatQuery](https://sm.alliedmods.net/new-api/dbi/SQL_FormatQuery)?

**Comment by CrazyHackGUT** [comment]
I think, yes. We can use `SQL_FormatQuery()` in all places in code.
