### ISSUE TITLE
Add features bonus NameTag

### ISSUE THREAD

**Issue by ThanhByKyTa** [FD-Forks/Shop-Core#54]
I want member set Nametag. When member to nametag get additional credits.

**Comment by TiBarification** [comment]
Your purpose is not related to shop core. You need to write a module for that, which can distribute credits on your conditions. In your example when nametag is changed.

**Comment by ThanhByKyTa** [comment]
@TiBarification Can you give me info coder? .I paid for module this.

**Comment by TiBarification** [comment]
I recommend you http://dev-source.ru
