### ISSUE TITLE
Error data pack

### ISSUE THREAD

**Issue by xMaZax** [FD-Forks/Shop-Core#55]
SM 1.10

L 03/12/2019 - 21:12:53: [SM] Exception reported: Data pack operation is out of bounds.
L 03/12/2019 - 21:12:53: [SM] Blaming: shop/shop.smx
L 03/12/2019 - 21:12:53: [SM] Call stack trace:
L 03/12/2019 - 21:12:53: [SM]   [0] DataPack.ReadFunction
L 03/12/2019 - 21:12:53: [SM]   [1] Line 560, E:\Other\CSGO\Compilator\sourcemod-1.10.0-git6381-linux\shop/db.sp::DB_RunBackup
L 03/12/2019 - 21:12:53: [SM]   [2] Line 335, E:\Other\CSGO\Compilator\sourcemod-1.10.0-git6381-linux\shop/db.sp::DB_CheckTable

**Comment by TiBarification** [comment]
Мы не поддерживаем версии скомпилированные вами вручную. Используйте те версии что билдит Travis в [Releases](../releases)
