### ISSUE TITLE
Invalid Handle 54a7123e

### ISSUE THREAD

**Issue by xSL0W** [FD-Forks/Shop-Core#58]
Hello, I am using the latest version of shop core and I have this error.

L 04/12/2019 - 13:43:57: [SM] Blaming: shop/@shop_core.smx
L 04/12/2019 - 13:43:57: [SM] Call stack trace:
L 04/12/2019 - 13:43:57: [SM]   [0] ArrayList.FindValue
L 04/12/2019 - 13:43:57: [SM]   [1] Line 718, addons/sourcemod/scripting/shop/item_manager.sp::ItemManager_OnItemRegistered

 - OS: Linux
    SourceMod Version: 1.9.0.6276
    SourcePawn Engine: 1.9.0.6276, jit-x86 (build 1.9.0.6276)
    Build ID: 6276:2bfc349

Modules list: 
http://prntscr.com/naz2vk
+
http://prntscr.com/naz372 (some plugins for gambling, like roulette, etc)

**Comment by TiBarification** [comment]
In which situation that error appears?

**Comment by xSL0W** [comment]
I don't know how to reproduce the bug, if I will find i will tell you

**Comment by xSL0W** [comment]
@TiBarification, nearly every map change I have 4 errors like the one posted.

**Comment by TiBarification** [comment]
@xSL0W try to unload one by one module and see what happens.

**Comment by TiBarification** [comment]
Seems that your database is corrupted, you doesn't have a **primary key** on column **id** of **items** table.
Maybe you migrated from one database to another?

In the next version i will add a check for it.
[shop_3.0D2-A.zip](https://github.com/FD-Forks/Shop-Core/files/3077876/shop_3.0D2-A.zip)

**Comment by xSL0W** [comment]
Yes, I migrated from zephyrus store

**Comment by xSL0W** [comment]
Here's my structure: http://prntscr.com/ncsre0
When I moved from zephyrus store to yours I only modified from "store_players" to "shop_players" and database structure. Here's my new "shop_players" that I created: http://prntscr.com/ncsrww
shop_bought, shop_items, shop_toggles were created by shop core

**Comment by xSL0W** [comment]
any ideea why it still gives errors?

**Comment by TiBarification** [comment]
I can't reproduce this error

**Comment by xSL0W** [comment]
Will it help if I give you my entire shop configuration? (database included)

**Comment by TiBarification** [comment]
> 
> 
> Will it help if I give you my entire shop configuration? (database included)

It may help. Send me on my mail tishinab2@gmail.com

**Comment by xSL0W** [comment]
> > Will it help if I give you my entire shop configuration? (database included)
> 
> It may help. Send me on my mail [tishinab2@gmail.com](mailto:tishinab2@gmail.com)

These plugins: goldmember, new_capsipajura, new_roulette, new_dailycredits_mysql and new_vip_credits are plugins related to gamble credits & plugins to give credits using natives of the shop.

**Comment by xSL0W** [comment]
Fixed it by removing module shop_new_weapons [ https://hlmod.ru/resources/shop-buy-new-weapons.1073/ ]

**Comment by R1KO** [comment]
@xSL0W check this https://hlmod.ru/threads/shop-buy-new-weapons.47486/page-3#post-407008

**Comment by xSL0W** [comment]
@R1KO i tested the plugin and it works like a charm
