### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by R1KO** [FD-Forks/Shop-Core#66]
> L 12/14/2019 - 17:59:36: [SM] Exception reported: Invalid Handle 9a10879 (error: 1)
> L 12/14/2019 - 17:59:36: [SM] Blaming: shop.smx
> L 12/14/2019 - 17:59:36: [SM] Call stack trace:
> L 12/14/2019 - 17:59:36: [SM]   [0] ArrayList.FindValue
> L 12/14/2019 - 17:59:36: [SM]   [1] Line 659, addons/sourcemod/scripting/shop/item_manager.sp::ItemManager_OnItemRegistered

- "[Shop] Neon" (1.3.0) by White Wolf & R1KO (HLModders LLC)
- "[Shop] Money Distributor" (1.4.3) by FrozDark (HLModders LLC)
- "[Shop] Logs" (1.2) by R1KO (skype: vova.andrienko1)
- "[Shop] Core" (3.0D4) by FrozDark (Fork by R1KO & White Wolf)
- "[Shop] Double Jump" (1.1) by R1KO - удалил
- "[Shop] Trails" (2.2.3) by FrozDark (HLModders LLC)
- "[CS:GO] Spritetrail fix" (1.0.1) by FrozDark
- "[Shop] Aura" (1.1) by R1KO and FIX AZA
- "[Shop/ZR] First Zombie Inmunity (PRIVATE)" (1.0) by R1KO (original by Franc1sco franug)
- "[Shop] Glow" (1.0.2) by Drumanid (plugin  alteration | [Shop] Neon White Wolf (HLModders LLC))
- "[Shop] Color Tracers" (2.0.3) by FrozDark & R1KO (HLModders LLC)

 **SourceMod (1.10.0.6458)**

Пока что еще не понял когда вылетает.

**Comment by TiBarification** [comment]
unexpected behaviour, so close for now
