### ISSUE TITLE
"Luck" update

### ISSUE THREAD

**Issue by IL0co** [FD-Forks/Shop-Core#68]
**Фиксы:**
- если sm_shop_luck_chance == 0 ИЛИ luck у игрока == 0 (-1), то убрать из меню данную функция (выключить её).
- сделать нормальный вывод процента удачи в меню шопа, брать значение из значения игрока (личного, а не общего).
- значение luck_chance из int сделать float (%3.2f)

**Добавить:**
- бесплатные попытки (если они есть у игрока, то использовать их, если нету, то платные)

**По API:**
[shop_api_add.txt](https://github.com/FD-Forks/Shop-Core/files/4160994/shop_api_add.txt)

**Comment by R1KO** [comment]
> * значение luck_chance из int сделать float (%3.2f)

Зачем? если шанс это процент от 0 до 100?

**Comment by IL0co** [comment]
> > * значение luck_chance из int сделать float (%3.2f)
> 
> Зачем? если шанс это процент от 0 до 100?

Что бы была больше возможность контроля процента в модулях.

**Comment by R1KO** [comment]
ну типо на диапазоне 0-100, десятые части не особо влияют

**Comment by IL0co** [comment]
> ну типо на диапазоне 0-100, десятые части не особо влияют
нуууууу, пожалуй да, мало на что оно будет влиять, пожалуй, пока что, не стоит его трогать

**Comment by TiBarification** [comment]
What behaviour of free luck, why luck part must be separated to free and not free?

**Comment by TiBarification** [comment]
With the least pain we can override function below with much more functionality, but implementing additional behaviour such as LuckState I don't see any reason to do that inside the core.
```h
/**
 *	Player is about to become winner
 *	-
 *	@param client			client index
 *	@param luck_chance		luck chance (by reference)
 *	@param item_id			Item id
 *	-
 *	@return Plugin_Changed to apply custom changes. >= Plugin_Handled to block, Plugin_Continue - to proceed without changes.
*/
forward Action Shop_OnClientShouldLuckItem(int client, float luck_chance, ItemId item_id);
```

**Comment by R1KO** [comment]
я думаю лучше так:
`forward Action Shop_OnClientShouldLuckItem(int client, int & iLuckChance, ItemId item_id);`

**Comment by R1KO** [comment]
И то. там 2 этапа выпадения:
1. определяет выпадет ли что либо игроку вообще
2. для конкретного предмета.
и это всё нужно учесть

**Comment by TiBarification** [comment]
> я думаю лучше так:
> `forward Action Shop_OnClientShouldLuckItem(int client, int & iLuckChance, ItemId item_id);`

Yeah, i forgot to add `&`

**Comment by IL0co** [comment]
> With the least pain we can override function below with much more functionality, but implementing additional behaviour such as LuckState I don't see any reason to do that inside the core.
> 
> ```c
> /**
>  *	Player is about to become winner
>  *	-
>  *	@param client			client index
>  *	@param luck_chance		luck chance (by reference)
>  *	@param item_id			Item id
>  *	-
>  *	@return Plugin_Changed to apply custom changes. >= Plugin_Handled to block, Plugin_Continue - to proceed without changes.
> */
> forward Action Shop_OnClientShouldLuckItem(int client, float luck_chance, ItemId item_id);
> ```

Я имею ввиду, что бы добавить FREE билетики, за которые игрок сможет бесплатно крутануть колесо удачи (билетик тратится в любом случае).

**Comment by TiBarification** [comment]
> 
> 
> > With the least pain we can override function below with much more functionality, but implementing additional behaviour such as LuckState I don't see any reason to do that inside the core.
> > ```c
> > /**
> >  *	Player is about to become winner
> >  *	-
> >  *	@param client			client index
> >  *	@param luck_chance		luck chance (by reference)
> >  *	@param item_id			Item id
> >  *	-
> >  *	@return Plugin_Changed to apply custom changes. >= Plugin_Handled to block, Plugin_Continue - to proceed without changes.
> > */
> > forward Action Shop_OnClientShouldLuckItem(int client, float luck_chance, ItemId item_id);
> > ```
> 
> Я имею ввиду, что бы добавить FREE билетики, за которые игрок сможет бесплатно крутануть колесо удачи (билетик тратится в любом случае).
I do not see any plans on this feature. Plugin will gain unnecessary complexity.

**Comment by TiBarification** [comment]
Here it comes...

2bcbab4
