### ISSUE TITLE
Ошибка бд

### ISSUE THREAD

**Issue by QwertiTarantino** [FD-Forks/Shop-Core#69]
С разными базами данных выдает эти ошибки

L 02/16/2020 - 03:16:02: [shop/shop.smx] DB_ErrorCheck: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IGNORE TABLE `shop_players` ADD `lastconnect` int(10) NOT NULL DEFAULT '0'' at line 1
L 02/16/2020 - 03:16:02: [shop/shop.smx] DB_UgradeState_1: Table '4v1u8x4r.shop_items' doesn't exist

L 02/16/2020 - 03:21:40: [shop/shop.smx] DB_ErrorCheck: Table '4v1u8x4r.shop_players' doesn't exist
L 02/16/2020 - 03:21:40: [shop/shop.smx] DB_UgradeState_1: Table '4v1u8x4r.shop_items' doesn't exist

**Comment by TiBarification** [comment]
Not enough data to reproduce

**Comment by QwertiTarantino** [comment]
Сначала я обновил старый плагин (3.0D4) на новый (3.0D5)
Потом я удалил все бд и установил новый плагин и вот эти ошибки
