### ISSUE TITLE
Adding a cookie analog to the database

### ISSUE THREAD

**Issue by IL0co** [FD-Forks/Shop-Core#79]
Add the ability to specify "any_data" to the player's item so that it can be read from other servers to which this database is attached. An analogue of *сlientprefs* in fact

![image](https://user-images.githubusercontent.com/50996383/90233598-107deb80-de27-11ea-8127-c9da12f79956.png)

**Comment by R1KO** [comment]
Слишком специфический функционал чтобы добавлять его в кор
