### ISSUE TITLE
shop bugs related to inventory and players

### ISSUE THREAD

**Issue by xSL0W** [FD-Forks/Shop-Core#93]
Hello. Some people reported bugs like this on my servers:
* When I give credits to all online players, using sm_givecredits @all 20000 some people will not get credits. Happened many times and it happened to me too. (average online players when I do this is 40)
* Some people, after they trade a shop item sometimes (rarely) it will not be saved in shop inventory
* Using a custom module, when I give a player an item sometimes (rarely) it will be not saved in shop inventory

ERROR: [shop/shop.smx] DB_ErrorCheck: Data too long for column 'name' at row 1
Happens if the player has a long name (32 characters, I think)

 - OS: linux debian 10
 - Sourcemod version 1.10.0.6501
 - Version 3.0E2

PS:
I only modified this line ( https://github.com/FD-Forks/Shop-Core/blob/master/addons/sourcemod/scripting/shop/player_manager.sp#L743 ) as a personal preference.

from 
`ToggleItemEx(client, sItemId, Toggle_On, true, true);`
to
`ToggleItemEx(client, sItemId, Toggle_Off, true, true);`

**Comment by xSL0W** [comment]
Using built-in transfer item system will trigger this problem too. The item just dissapears.

**Comment by TiBarification** [comment]
>Happens if the player has a long name (32 characters, I think)

Buffer for player name is exactly 32 characters, so i don't think that is was a problem.

>I only modified this line

It is not related to this problem.

What database you're using for shop?

**Comment by TiBarification** [comment]
Also attach your columns in `shop_players` table with type properties.

**Comment by xSL0W** [comment]
> Also attach your columns in shop_players table with type properties.

Hello, I uploaded all the structure here of all columns, do you want data too?
[go.sql.zip](https://github.com/FD-Forks/Shop-Core/files/5978335/go.sql.zip)

> What database you're using for shop?

I am using mariadb 
Server version: 10.3.25-MariaDB-0+deb10u1 - Debian 10
InnoDB only
https://prnt.sc/zic3l1
https://prnt.sc/zic4qo

> Buffer for player name is exactly 32 characters, so i don't think that is was a problem.

I just believe it, the player had a very long name.
Maybe 32 + 1 will fix it, I don't know.

**Comment by TiBarification** [comment]
You have corrupted table structure, shop automatically creates table with query
```sql
CREATE TABLE IF NOT EXISTS `shop_players` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL DEFAULT 'unknown',
  `auth` varchar(22) NOT NULL,
  `money` int NOT NULL,
  `lastconnect` int,
  PRIMARY KEY (`id`),
  UNIQUE KEY `auth` (`auth`) 
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
```

>I uploaded all the structure here of all columns, do you want data too?
go.sql.zip

Your structure (from file) is:
```sql
CREATE TABLE `shop_players` (
  `id` int(11) NOT NULL,
  `name` varbinary(255) DEFAULT NULL,
  `auth` varchar(22) NOT NULL,
  `money` int(11) NOT NULL,
  `lastconnect` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Do you see difference? Of course it will work incorrectly, at least in a structure definition. You need to fix issues with your tables structure.

**Comment by xSL0W** [comment]
Hello! Im coming back with a feedback after I will remake the structure again.
Can this problem affect Shop_GiveClientItem function? Or the built-in trade system?

**Comment by TiBarification** [comment]
> 
> 
> Hello! Im coming back with a feedback after I will remake the structure again.
> Can this problem affect Shop_GiveClientItem function? Or the built-in trade system?

Any database change which related to shop database can cause problems with any plugin functional. So do not try to modify database unless you know what you do.

Answering to your question, yes, if your structure was changed it may cause plugin to work incorrectly.

**Comment by xSL0W** [comment]
Hello. This is why i changed my database structure, because of this error.
`L 02/16/2021 - 03:49:50: [shop/shop.smx] DB_ErrorCheck: Incorrect string value: '\xF0\x9D\x95\xAE\xF0\x9D...' for column `go`.`shop_players`.`name` at row 1
`
Changing from varchar to varbinary will solve it.


Server version: 10.3.27-MariaDB-0+deb10u1-log - Debian 10
Server charset: UTF-8 Unicode (utf8mb4)

**Comment by xSL0W** [comment]
Changed database charsets and collations to utf8mb4 and utf8mb4_unicode_ci to all tables. I think it works.
