### ISSUE TITLE
Documentation bad

### ISSUE THREAD

**Issue by bobitza** [FD-Forks/Shop-Core#94]
Hi the documentation is very bad i don't understand how to use this plugin and how to create Items like Weapons skins in category Weapons Skins
I'm need to create new plugin and include that forwards ?
Do you have an example of plugin that can create a category named Weapons Skins and insert like Weapons plugin items ?
Like 
`		"M4A1-S Hyper Beast"
		{
			"paint"	 "430"
			"wear"	 "0.01"
			"stattrak" "1"
			"quality" "3"
			"type" "weaponskin"
			"price" "100"
			"unique_id" "weapon_m4a1_silencer_430"
		}`
To corelate with Weapons plugin 	name = "Weapons & Knives",
	author = "kgns | oyunhost.net",

**Comment by TiBarification** [comment]
> 
> 
> Hi the documentation is very bad i don't understand how to use this plugin and how to create Items like Weapons skins in category Weapons Skins
>

Did you read the [official docs](https://fd-forks.github.io/Shop-Core/module/create/) on module creation?

**Comment by bobitza** [comment]
Both, no demos ...

**Comment by TiBarification** [comment]
I confirm, there no example of using natives to create item by time expiration or that kind of stuff. I think i will find time to add more examples, based on existing plugins.
