### ISSUE TITLE
Function prototype different

### ISSUE THREAD

**Issue by bobitza** [FD-Forks/Shop-Core#98]
**Describe the bug**
When i try to create a callback function to Preview forward i recieve this error :**error 100: function prototypes do not match** what i do wrong ?
Error is on line with Shop_SetCallbacks when i put my function OnPreviewItemEx

![image](https://user-images.githubusercontent.com/1919467/110074313-aceae980-7d89-11eb-85ee-94dc85bc1589.png)

**Comment by bobitza** [comment]
I found the problem public function OnPreviewItemEx need to be of type void not ShopAction buy in DOCUMENTATION didn't telled that i haved to find in includes how you declare..

For who will have problem put this in doc:
`
typeset Shop_ItemUseToggleCallback
{
	function ShopAction (int client, CategoryId category_id, const char[] category, ItemId item_id, const char[] item);
	function ShopAction (int client, CategoryId category_id, const char[] category, ItemId item_id, const char[] item, bool isOn, bool elapsed);
}
typedef Shop_ItemRegister = function void (CategoryId category_id, const char[] category, const char[] item, ItemId item_id);
typedef Shop_ItemCommon = function void(int client, CategoryId category_id, const char[] category, ItemId item_id, const char[] item);
typedef Shop_ItemShouldDisplayCallback = function bool (int client, CategoryId category_id, const char[] category, ItemId item_id, const char[] item, ShopMenu menu);
typedef Shop_ItemDisplayCallback = function bool (int client, CategoryId category_id, const char[] category, ItemId item_id, const char[] item, ShopMenu menu, bool &disabled, const char[] name, char[] buffer, int maxlen);
typedef Shop_ItemDescriptionCallback = function bool (int client, CategoryId category_id, const char[] category, ItemId item_id, const char[] item, ShopMenu menu, const char[] description, char[] buffer, int maxlen);
`

**Comment by R1KO** [comment]
This is described in the documentation:

https://github.com/FD-Forks/Shop-Core/blob/master/addons/sourcemod/scripting/include/shop/register.inc#L114
https://github.com/FD-Forks/Shop-Core/blob/master/addons/sourcemod/scripting/include/shop/register.inc#L12
